# Generated by Django 4.2 on 2025-05-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=3)),
                ('empname', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('joindate', models.CharField(max_length=10)),
            ],
        ),
    ]
