# Generated by Django 4.2 on 2025-05-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
